-- Tabla para guardar el historial de chat por usuario
CREATE TABLE IF NOT EXISTS chat_history (
    id bigint generated by default as identity primary key,
    user_id bigint references usuarios(user_id) on delete cascade,
    role text not null check (role in ('user', 'assistant')),
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Índice para búsquedas rápidas por usuario
CREATE INDEX IF NOT EXISTS idx_chat_history_user_created ON chat_history(user_id, created_at DESC);
