-- Table to track user progress in learning modules
CREATE TABLE IF NOT EXISTS user_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    module_id INT NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, module_id)
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_user_modules_user_id ON user_modules(user_id);
