-- Add ai_usage_count to usuarios
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ai_usage_count INT DEFAULT 0;

-- Table for Badges Definitions
CREATE TABLE IF NOT EXISTS badges (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    icon TEXT, -- Emoji or short code
    category TEXT -- 'learning', 'lab', 'ai', 'general'
);

-- Table for User Badges
CREATE TABLE IF NOT EXISTS user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    badge_id INT REFERENCES badges(id),
    awarded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, badge_id)
);

-- Insert Default Badges
INSERT INTO badges (name, description, icon, category) VALUES
('Iniciado', 'Completó el primer módulo de entrenamiento.', '🌱', 'learning'),
('Hacker Novato', 'Completó 3 módulos de entrenamiento.', '💻', 'learning'),
('Script Kiddie', 'Completó 5 módulos de entrenamiento.', '👾', 'learning'),
('White Hat', 'Completó todos los módulos de entrenamiento.', '🎩', 'learning'),
('Explorador', 'Realizó su primer escaneo de red en laboratorio.', '🔭', 'lab'),
('Curioso', 'Realizó 10 consultas a la IA.', '🤖', 'ai'),
('Investigador', 'Realizó 50 consultas a la IA.', '🔍', 'ai')
ON CONFLICT (name) DO NOTHING;
