-- Tabla para registrar el progreso de los laboratorios prácticos
CREATE TABLE IF NOT EXISTS user_labs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES usuarios(user_id),
    lab_id INTEGER NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, lab_id)
);

-- Índices para búsqueda rápida
CREATE INDEX IF NOT EXISTS idx_user_labs_user_id ON user_labs(user_id);
